# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd461639d66b7e965eda7a00e06f94afdc5176c36ce186169e3bc19f95671ebe41927b0c56de07433d0bceaf7ab6c4bac0f5f98efb024540f628a15dba5c9131

test:
  secret_key_base: bcb3c720c22c9e8e5d004421c1fd4e97b87627770d566a0f4fe7a5952396ab2ea17603eab8e10dc45443089916f5501125a8c92d00341e67df3a6bd59887cd53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
